confab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qa.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('confab_auth.urls')),

    path('users/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from .views import home, question, ask, delete, edit, create_category, \
    serve_categories, QuestionLikeRedirect, QAnsweredRedirect, activity
from . import views



app_name="qa"
urlpatterns = [
    path('', home, name='home'),
    path('question/<int:qn_id>/', question, name='question'),
    path('question/<int:qn_id>/like/', QuestionLikeRedirect.as_view(), name='like'),
    path('answer/<int:a_id>/best/', QAnsweredRedirect.as_view(), name='best_answer'),
    path('question/', home),
    path('author/<int:a_id>/', home, name='author'),
    path('categories/', serve_categories, name='categories'),
    path('category/<int:a_id>', home, name='category'),
    path('create_category/', create_category, name='create_category'),
    path('popular/', home, name='popular'),
    path('ask/', ask, name='ask'),
    path('delete/<str:obj_type>/<int:o_id>', delete, name='delete'),
    path('edit/<str:obj_type>/<int:o_id>', edit, name='edit'),
    path('activity/<int:auth_id>/', activity, name='activity'),
    path('contactus', views.contactus, name='contactus'),
    path('about_us', views.about_us, name='about_us'),
    path('Feedback', views.Feedback, name='Feedback'),

]

qa/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User as CustomUser
# from users.models import CustomUser


class QuestionManager(models.Manager):
    def new(self):
        return self.order_by('-added_at')

    def popular(self, limit=None):
        return self.order_by('-rating')[:limit] if limit else self.order_by('-rating')

    def get_starred(self, user):
        return self.filter(likes=user)


class QuestionCategoryManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)

    @staticmethod
    def popular_categories():
        # this method will return top 5 categories
        c = Category.objects.annotate(num_questions=models.Count('question'))
        cat = c.order_by('-num_questions')[:5]
        return cat


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.CharField(max_length=255, null=True, blank=True)

    objects = QuestionCategoryManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return self.slug

    def get_url(self):
        return f"/category/{self.id}"

    def get_number(self):
        # this method returns a number of related questions
        c = Category.objects.annotate(num_questions=models.Count('question')).filter(id=self.id)
        return c[0].num_questions

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name) + str(self.id)
        super(Category, self).save(*args, **kwargs)


class Question(models.Model):
    title = models.CharField(blank=False, null=False, max_length=255)
    text = models.TextField()
    added_at = models.DateField(auto_now=True)
    edited_at = models.DateField(blank=True, null=True)
    author = models.ForeignKey(CustomUser, on_delete=models.SET(value='Deleted'))
    rating = models.IntegerField(default=0, blank=True)
    likes = models.ManyToManyField(CustomUser, related_name='get_likes', blank=True)
    category = models.ManyToManyField(Category, blank=True)

    objects = QuestionManager()

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse('qa:question', kwargs={'qn_id': self.id})

    def get_like_toggle(self):
        print("THIS::", self.id)
        return reverse('qa:like', kwargs={'qn_id': self.id})

    def has_answer(self):
        res = len(self.answer_set.filter(best_answer=True))
        return True if res > 0 else False


class Answer(models.Model):
    added_at = models.DateField(auto_now=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.SET(value='Deleted'))
    text = models.TextField(null=True)

    active = models.BooleanField(default=True)  # added in case i'll need to deactivate some answers fsr
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies',
                               on_delete=models.CASCADE)  # deals with comments on answers

    best_answer = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.text

qa/forms.py
from django.forms import ModelForm
from .models import Question, Answer, Category

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field


class AskForm(ModelForm):
    """this is for creating new questions. Made it with ModelForm"""

    class Meta:
        """let's get field names from the model"""
        model = Question
        fields = ['title', 'text', 'author', 'category']
        exclude = ('author',)  # need to exclude this to pre-save form


class AnswerForm(ModelForm):
    """this is an answer form"""

    def __init__(self, *args, **kwargs):
        """here I am using the FormHelper class and its attributes to make the form look nicer"""

        super(AnswerForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = "form-control"
        self.helper.form_id = 'id-answerForm'
        self.helper.layout = Layout(
            Field('text', style="height:15ch"),
        )

        self.helper.add_input(Submit('submit', 'Add Answer'))
        self.helper.form_show_labels = False  # don't want it to draw the actual model field name

    class Meta:
        model = Answer
        fields = ['text']
        exclude = ('author', 'question')


class CategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = ['name', 'description']

qa/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.views.generic import RedirectView

from .models import Question, Answer, Category
# from users.models import CustomUser
from django.contrib.auth.models import User as CustomUser
from .forms import AskForm, AnswerForm, CategoryForm


def home(request, a_id=None):
    """Here we're trying to serve two urls with one view: / and popular"""
    if(not request.user.is_authenticated):
        return redirect('signin')
    new_questions = Question.objects.new()
    top = Question.objects.popular(5)
    pref = ''
    title = 'Main Page: Most Recent'

    if 'popular' in request.path:
        # this part would return 'popular questions', sorted by rating field
        new_questions = Question.objects.popular()
        pref = '/popular/'
        title = 'Most Popular'

    if 'author' in request.path and a_id:
        # this case returns Questions by an Author chosen by an a_id
        auth = get_object_or_404(CustomUser, id=a_id)
        new_questions = auth.question_set.new()
        title = f'Questions by {auth.username}'

    if 'category' in request.path and a_id:
        cat = get_object_or_404(Category, id=a_id)
        new_questions = cat.question_set.new()
        title = f'Category: {cat.name}'

    if 'search' in request.GET:
        search_term = request.GET['search']
        new_questions = new_questions.filter(title__icontains=search_term) | \
                        new_questions.filter(text__icontains=search_term)
        title = f'Search results for {search_term}'
    is_all=True
    if 'college_filter' in request.GET:
        college_filter = request.GET['college_filter']
        if(college_filter != 'all'):
            is_all=False
            new_questions = Question.objects.filter(author__account__university=college_filter)
        title = college_filter.replace("_", " ").title()

    # let's create a paginator object
    limit = request.GET.get('limit', 10)
    page = int(request.GET.get('page', 1))
    paginator = Paginator(new_questions, limit)
    paginator.baseurl = pref + '?page='
    try:
        # try to deliver a page.
        questions = paginator.page(page)

    except EmptyPage:
        # If the page is out of range (e.g. 9999), serve the last one available.
        questions = paginator.page(paginator.num_pages)


    return render(request, 'qa/questions.html', {
        'questions': questions,
        'paginator': paginator,
        'title': title,
        'top': top,
        'top_categories': Category.objects.popular_categories(),
        'is_all': is_all
    })


def question(request, qn_id):
    """this view will return a single question + related answers by id and CREATE answers"""

    qn = get_object_or_404(Question, id=qn_id)
    top = Question.objects.popular(5)
    # list of active parent answers
    answers = qn.answer_set.filter(active=True, parent__isnull=True)
    ans_form = AnswerForm()

    if request.method == 'POST':
        # here is an answer form call(by question id)
        if request.user.is_authenticated:
            ans_form = AnswerForm(request.POST)

            if ans_form.is_valid():

                # here is a code for replies on answers (answers have 'parents'). It works (mostly),\
                # but I am not so sure if this feature is still relevant: think it over later

                try:  # get parent comment id from hidden input
                    parent_id = request.POST.get('parent_id')
                except (KeyError,):
                    parent_id = None

                if parent_id:  # if parent_id has been submitted get parent_obj id
                    parent_obj = Answer.objects.get(id=parent_id)
                    if parent_obj:  # if parent object exist
                        reply_answer = ans_form.save(commit=False)  # create reply object
                        reply_answer.parent = parent_obj  # assign parent_obj to reply
                        # end of the sub-answers code

                # normal answer (without 'parents')
                ans_form = ans_form.save(commit=False)
                # pre-save form, but don't commit changes to the DB yet
                ans_form.author = request.user
                ans_form.question = qn
                # here we are adding user and question objects to the form and finally save it to the DB
                ans_form.save()

            return redirect(qn.get_url())

        else:
            m = messages.warning(request, 'Sorry! You have to login first!')
            return redirect(f'/auth/signin?next={qn.get_url()}', m)
    print("QN::", qn.get_like_toggle)
    return render(request, 'qa/question.html', {'qn': qn, 'answers': answers,
                                                'ans_form': ans_form, 'top': top,
                                                'top_categories': Category.objects.popular_categories(), })


class QuestionLikeRedirect(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        qn_id = self.kwargs.get('qn_id')
        qn = get_object_or_404(Question, pk=qn_id)
        url_ = qn.get_url()
        user = self.request.user

        if user.is_authenticated:

            if user in qn.likes.all():
                qn.likes.remove(user)
                qn.rating -= 1
            else:
                qn.likes.add(user)
                qn.rating += 1

            qn.save()

        return url_


class QAnsweredRedirect(RedirectView):
    # here a question author can assign a
    # 'best answer' badge (and cancel it)

    def get_redirect_url(self, *args, **kwargs):
        a_id = self.kwargs.get('a_id')
        ans = get_object_or_404(Answer, id=a_id)
        url_ = ans.question.get_url()
        user = self.request.user
        if user.is_authenticated and user == ans.question.author:
            if ans.best_answer:
                ans.best_answer = False
            else:
                ans.best_answer = True
            ans.save()
        return url_


@login_required
def ask(request):
    """create new question"""

    if request.method == 'POST':
        form = AskForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.author = request.user
            f.save()

            # When using commit=False, we have to call save_m2m() manually
            # m2m relationships require the parent object to be saved first
            # maybe it is best to move the whole thing to the forms
            # obviously the view is getting to fat

            form.save_m2m()
            m = messages.success(request, 'OK! The question was created')
            return redirect(f.get_url(), m)
    else:
        form = AskForm()

    return render(request, 'qa/askform.html', {'form': form})


@login_required
def delete(request, obj_type, o_id):
    """ this view simply deletes both Questions, Answers and Categories"""

    choose = {'q': [Question, 'question', '/'],
              'a': [Answer, 'answer', ''],
              'c': [Category, 'category', '/categories'], }
    try:
        obj = get_object_or_404(choose[obj_type][0], id=o_id)
        permission = True if obj_type == 'c' else obj.author == request.user
        if request.method == "POST" and permission:
            obj.delete()
            m = messages.success(request, f'OK! The {choose[obj_type][1]} was deleted')
            return HttpResponseRedirect(choose[obj_type][2], m) if obj_type in ['q', 'c'] \
                else redirect(obj.question.get_url(), m)
    except (KeyError,):
        return redirect('/')


@login_required
def edit(request, obj_type, o_id):
    """this is edit view for both Questions and Answers"""

    choose = {'q': [Question, AskForm, 'qa/askform.html', 'question'],
              'a': [Answer, AnswerForm, 'qa/edit.html', 'answer'],
              'c': [Category, CategoryForm, 'qa/askform.html', 'category']}

    try:
        obj = get_object_or_404(choose[obj_type][0], id=o_id)
        # now let's decide if the user can edit the object at all
        permission = True if obj_type == 'c' else obj.author == request.user
        red = '/categories'  # redirect afterwards

        if request.method == "POST" and permission:
            form = choose[obj_type][1](request.POST, instance=obj)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.added_at = timezone.now()
                m = messages.success(request, f"The {choose[obj_type][3]} was successfully edited")
                obj.save()
                form.save_m2m()

                if obj_type != 'c':
                    red = obj.get_url() if obj_type == 'q' else obj.question.get_url()

                return HttpResponseRedirect(red, m)
        else:
            form = choose[obj_type][1](instance=obj)

        return render(request, choose[obj_type][2], {'form': form})

    except (KeyError,):
        raise Http404


@login_required
def create_category(request):
    # with this view we create new category objects, login required

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            m = messages.success(request, f'Success! You\'ve just created a new category!')
            return HttpResponseRedirect('/categories', m)
    else:
        form = CategoryForm()

    return render(request, 'qa/askform.html', {'form': form})


def serve_categories(request):
    # the view will basically return a list of all categories ordered by id

    cat = Category.objects.all().order_by('id')
    top = Question.objects.popular(5)  # this is shown on the right widget

    title = 'Categories'
    limit = request.GET.get('limit', 10)

templates/qa/Feedback.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="Logo.png" type="image/x-icon">
    <link href='https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;700&display=swap' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css2?family=Jockey+One&family=Poppins:wght@100;300;400;500;700&family=Roboto:wght@100;300&display=swap' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css2?family=Jockey+One&family=Roboto:wght@100;300&display=swap' rel='stylesheet'>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- link awesome icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <title>CONFAB: Feedback</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        
        body {
            height: 100vh;
            font-family: 'Poppins', sans-serif;
        }
        
        .header__main {
            width: 100vw;
            height: 4rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 3rem;
            background-color: #EDF2F6;
        }
        
        .header__main h2 {
            font-family: 'Jockey One', sans-serif;
            color: #5C5C5C;
        }
        
        .header__main span {
            font-size: 3rem;
            font-family: 'Roboto';
            font-weight: 1000;
            color: #00C897;
        }
        
        .heading {
            font-weight: 600;
            font-size: 20px;
            text-align: center;
        }
        
        .container .top {
            text-align: center;
            font-size: 40px;
            font-weight: 800;
            text-decoration: underline;
        }
        
        .content {
            font-size: 20px;
            text-align: center;
        }
        
         ::-webkit-scrollbar {
            width: 20px;
        }
        
         ::-webkit-scrollbar-track {
            background-color: transparent;
        }
        
         ::-webkit-scrollbar-thumb {
            background-color: #d6dee1;
            border-radius: 20px;
            border: 6px solid transparent;
            background-clip: content-box;
        }
        
         ::-webkit-scrollbar-thumb:hover {
            background-color: #a8bbbf;
        }
        
        footer {
            font-family: 'Jockey One', sans-serif;
            position: absolute;
            bottom: -200px;
            left: 0;
            right: 0;
            background: #00D19E;
            height: auto;
            width: 100vw;
            padding-top: 40px;
            color: #fff;
        }
        
        .footer-content {
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            text-align: center;
        }
        /* .footer-content h3 {
    margin: 10px auto;
    font-family: sans-serif;
    font-size: 2.1rem;
    font-weight: 500;
    text-transform: capitalize;
    line-height: 3rem;
} */
        
        .footer h2 {
            font-family: 'Jockey One', sans-serif;
            color: #5C5C5C;
        }
        
        .footer span {
            font-size: 3rem;
            font-family: 'Roboto';
            font-weight: 1000;
            color: #00C897;
        }
        
        .footer-content p {
            font-family: sans-serif;
            max-width: 700px;
            margin: 10px auto;
            line-height: 28px;
            font-size: 14px;
            color: #ffffff;
        }
        
        .socials {
            list-style: none;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 1rem 0 3rem 0;
        }
        
        .socials li {
            margin: 0 10px;
        }
        
        .socials a {
            text-decoration: none;
            color: #fff;
            border: 1.1px solid white;
            padding: 5px;
            border-radius: 50%;
        }
        
        .socials a i {
            font-size: 1.1rem;
            width: 20px;
            transition: color .4s ease;
        }
        
        .socials a:hover i {
            color: #049e77;
            ;
        }
        
        .footer-bottom {
            background: #00D19E;
            width: 100vw;
            padding: 20px;
            padding-bottom: 40px;
            text-align: center;
        }
        
        .footer-bottom p {
            float: left;
            font-size: 14px;
            word-spacing: 2px;
            text-transform: capitalize;
        }
        
        .footer-bottom p a {
            color: #ffffff;
            font-size: 16px;
            text-decoration: none;
        }
        
        .footer-bottom span {
            text-transform: uppercase;
            opacity: .4;
            font-weight: 200;
        }
        
        .footer-menu {
            float: right;
        }
        
        .footer-menu ul {
            display: flex;
        }
        
        .footer-menu ul li {
            padding-right: 10px;
            display: block;
        }
        
        .footer-menu ul li a {
            color: #ffffff;
            text-decoration: none;
        }
        
        .footer-menu ul li a:hover {
            color: #049e77;
            ;
        }
    </style>
</head>

<body>
    <header class="header__main">
        <!-- <img src="Rectangle 1.svg" alt="Rectangle" class="rectangle"> -->

        <a href="http://127.0.0.1:8000/"" style="text-decoration: none;">

            <h2><span>C</span>onfab</h2>

        </a>


    </header>

    <svg preserveAspectRatio="none" width="100VW" height="194" viewBox="0 0 1920 194" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect width="100VW" height="194" fill="white"/>
        <path d="M514.224 99.3881C607.024 80.3875 696.88 46.3306 789.424 25.6747C921.248 -3.76844 1058.53 -5.547 1190.14 24.9879C1318.05 54.5895 1450.67 126.789 1577.06 163.469C1689.14 196.012 1811.5 209.412 1920 168.752V0H0V48.162C163.945 116.582 341.781 134.298 514.224 99.3881Z" fill="#EDF2F6"/>
    </svg>

    <div class="container">
        <div class="top">
            Feedback<br><br>
        </div>
        <div class="heading">
            Hola Amigos!
        </div>
        <div class="content">
            We are glad that we were able to solve your problem today. <br> We sincerely accept your feedback on this email:
            <a href="mailto:feedback.confab420@confab.in "> feedback.confab420@confab.in</a>.

        </div>

    </div>
    <footer>
        <div class="footer-content">
            <h3><span>C</span>onfab</h3>

            <p>CONFAB is a Q&A forum where people of the same organisation can interact with each other with complete anonymity. </p>

            <ul class="socials">
                <li><a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                <li><a href="#"><i class="fa-brands fa-youtube"></i></a></li>
                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
            </ul>

        </div>
        <div class="footer-bottom">
            <p>copyright &copy;2022 <a href="#">CONFAB</a> </p>
            <div class="footer-menu">
                <ul class="f-menu">
			<li style="list-style: none;"><a href="/" style="color: black !important;padding: 0;">Home</a></li>
			<li style="list-style: none;"><a href="/about_us" style="color: black !important;padding: 0;">About</a></li>
			<li style="list-style: none;"><a href="/contactus" style="color: black !important;padding: 0;">Contact Us</a></li>
			<li style="list-style: none;"><a href="/feedback" style="color: black !important;padding: 0;">Feedback</a></li>
                </ul>
            </div>
        </div>

    </footer>
</body>

</html>

templates/qa/answer.html
{% load crispy_forms_tags %}

<div class="card my-4">
          <h5 class="card-header ">Leave an Answer</h5>
          <div class="card-body">

              <form class="uniForm" method="post" action="http://{{request.get_host}}/question/{{qn_id}}/">
                  {% csrf_token %}
                  {% crispy ans_form ans_form.helper %}
              </form>

          </div>
</div>

templates/qa/askform.html
{# This is to create new questions #}

{% extends "base.html" %}

{% block title %}Create New Question{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

    <form class="form-horizontal" method="POST">

     {{ form|crispy }}
     {% csrf_token %}

    <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save</button>
    </div>

    </form>

{% endblock %}

templates/qa/edit.html
{# this template is for editing a single answer: didn't want ajax for the case #}

{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
              <form class="uniForm" method="post">
                  {% csrf_token %}
                  {% crispy form form.helper %}
              </form>
{% endblock %}

templates/qa/question.html
{# This is a single question view template #}
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Question: {{ qn.title|truncatechars:30 }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-8">

        <!-- Question -->
        <h3 class="mt-4">{{ qn.title }}</h3>
        <div class="text-right">

                <div class="lead"> Posted by a student
                                              
                    {% comment %} {{ qn.author }}</a> on {{ qn.added_at }}&nbsp; {% endcomment %}
                                    <a href="{{ qn.get_like_toggle }}" class="btn btn-primary">
                    Likes <span class="badge badge-light">{{ qn.rating }}</span>
                </a>
                    <!--controls: question-->
                {% if request.user.id == qn.author.id %}
                            <div class="btn-group" role="group">
                                <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">edit
                                </button>
                                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                    <a class="dropdown-item" href="http://{{request.get_host}}/edit/q/{{ qn.id }}">Edit</a>
                                    <form action="{% url 'qa:delete' obj_type='q' o_id=qn.id %}" class="select2-dropdown"
                                          method="POST">
                                        {% csrf_token %}<input type="submit" value="Delete" class="dropdown-item"
                                                               data-toggle="tooltip" data-placement="top"
                                                               title="Delete the Question"/>
                                    </form>
                                </div>
                            </div>
                {% endif %}
                   {# controls: question end #}
                </div>
        </div>

        <div class="media border-bottom p-3">
           {{ qn.text }}
        </div>

       <!-- Tags -->
       <div class="d-inline mt-2">
            {% for c in qn.category.all %}
                       <a href="{{ c.get_url }}" class="badge bg-info text-white">{{ c.name }}</a>
            {% endfor %}
        </div>

        <!-- Answers -->
        {% for answer in answers %}

            {% if answer.best_answer %}
                <div class="media border border-success rounded p-3 my-3">
            {% else %}
                <div class="media  border-bottom border-left rounded p-3 my-3">
            {% endif %}

            <img src="/media/{{ answer.author.avatar }}" alt="" class="mr-3 mt-3 rounded-circle" style="width:60px;">
            <div class="media-body">
                <div class="row">
                    <div class="col-sm-10">
                                {% if answer.best_answer %}&nbsp;
                                    <a class="badge badge-success" href="{% url 'qa:best_answer' a_id=answer.id %}"
                                       data-toggle="tooltip" data-placement="right"
                                       title="The Questions's Author Marked This Answer as a Best One">
                                        Best Answer!</a>
                                {% else %}
                                    {% if request.user.id == answer.question.author.id %}
                                        <a class="badge badge-secondary" href="{% url 'qa:best_answer' a_id=answer.id %}">Upvote</a>
                                    {% endif %}
                                {% endif %}
                            </p>
                    </div>

                    {# controls: edit/delete answer #}
                    {% if request.user.id == answer.author.id %}
                    <div class="col-sm-2">
                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-info btn-secondary dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Edit
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" href="http://{{request.get_host}}/edit/a/{{ answer.id }}">Edit</a>
                                <form action="{% url 'qa:delete' obj_type='a' o_id=answer.id %}" class="select2-dropdown"
                                    method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Delete" class="dropdown-item" data-toggle="tooltip"
                                        data-placement="top" title="Delete the Answer" />
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {# controls answer: end #}
                {{ answer.text }}
            </div>
        </div>
        {% endfor %}
        {# answer: end #}

        <!-- AnswerForm -->
        {% include 'qa/answer.html' with form=ans_form qn_id=qn.id %}

    </div>
{% include 'right_bar.html' %}
</div>
</div>
{% endblock %}