confab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qa.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('confab_auth.urls')),

    path('users/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from .views import home, question, ask, delete, edit, create_category, \
    serve_categories, QuestionLikeRedirect, QAnsweredRedirect, activity
from . import views



app_name="qa"
urlpatterns = [
    path('', home, name='home'),
    path('question/<int:qn_id>/', question, name='question'),
    path('question/<int:qn_id>/like/', QuestionLikeRedirect.as_view(), name='like'),
    path('answer/<int:a_id>/best/', QAnsweredRedirect.as_view(), name='best_answer'),
    path('question/', home),
    path('author/<int:a_id>/', home, name='author'),
    path('categories/', serve_categories, name='categories'),
    path('category/<int:a_id>', home, name='category'),
    path('create_category/', create_category, name='create_category'),
    path('popular/', home, name='popular'),
    path('ask/', ask, name='ask'),
    path('delete/<str:obj_type>/<int:o_id>', delete, name='delete'),
    path('edit/<str:obj_type>/<int:o_id>', edit, name='edit'),
    path('activity/<int:auth_id>/', activity, name='activity'),
    path('contactus', views.contactus, name='contactus'),
    path('about_us', views.about_us, name='about_us'),
    path('Feedback', views.Feedback, name='Feedback'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    {% block meta_tags %}{% endblock %}

    <title>{% block title %}Welcome!{% endblock %}</title>

<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;

    }

    h2{
        padding-top: 25px;
    }

    footer {
        margin: auto auto 0 auto;
        width: 100%;
    }
</style>

    {% block stylesheets %}
    {% endblock %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
          <link rel="stylesheet" href="{% static 'styles/header.css' %}">
          <link rel="stylesheet" href="{% static 'styles/signin.css' %}">
      
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</head>
<body>
<header></header>

{% include 'components/header.html' %}
{% include 'messages.html' %}

<div id="main" role="main">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>

{% include 'footer.html' %}

</body>

</html>

templates/footer.html
 <!-- Footer -->
<footer class="py-2 px-3" style="background-color: #00C897;display: flex;align-items: center;justify-content: space-between;position: fixed;bottom: 0;width: 100vw;">

  <b class="text-white">Copyright &copy; @2022 Confab</b>

  <ul class="text-white" style="display: flex; align-items: center;gap: 1rem;text-decoration: none;color: black" >
    <li style="list-style: none;"><a href="/" style="color: black !important;padding: 0;">Home</a></li>
    <li style="list-style: none;"><a href="/about_us" style="color: black !important;padding: 0;">About</a></li>
    <li style="list-style: none;"><a href="/contactus" style="color: black !important;padding: 0;">Contact Us</a></li>
    <li style="list-style: none;"><a href="/Feedback" style="color: black !important;padding: 0;">Feedback</a></li>
  </ul>

</footer>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
{% if auth.user.is_authenticated %}
  Hi {{ auth.user.username }}!
  <p><a href="http://{{request.get_host}}/auth/logout/">Log Out</a></p>
{% else %}

  <p>You are not logged in</p>
  <a href="{% url 'signin' %}">Log In</a> | <a href="{% url 'verify_email'  %}">Sign Up</a>

{% endif %}
{% endblock content %}

templates/messages.html
{% for message in messages %}

<div class="row">
<div class="col-sm-1"></div>

    <div class="alert alert-{{ message.tags }} alert-dismissible fade show col-sm-10" align="center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ message }}</strong>
    </div>

</div>

{% endfor %}

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 fixed-top">
<div class="container">
    <a class="navbar-brand" href="{% url 'qa:home' %}">CONFAB</a>

   {% if title != 'Categories' %}
       <form class="form-inline mr-auto" action="{% url 'qa:ask' %}">
           <input class="btn btn-outline-success" type="submit" value="Create Question +"/>
       </form>

   {% endif %}

    <div>
        
        {% if request.user.is_authenticated %}
                    <a class="nav-link dropdown-toggle" href="" id="userMenu"
                       data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false" style='color: white'>
                        Hello, Smarty
                    </a>
                    <div class="dropdown-menu dropdown-menu-right"
                         aria-labelledby="userMenu">
                        <a class="dropdown-item" style="color: blue"
                           href="{% url 'qa:activity' auth_id=request.user.id %}">My activity</a>
                      
                        
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="http://{{request.get_host}}/auth/logout/">
                            Log Out</a>
                    </div>
        {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'signin' %}" class="btn btn-outline-secondary">
                    Log In</a>
                <a href="{% url 'verify_email' %}" class="btn btn-primary ml-2">
                    Sign up</a>
            </form>
        {% endif %}
    </div>
</div>
</nav>

templates/right_bar.html
   <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search by keywords</h5>
            <div class="card-body">
                <form id="searchform" method="GET" action="{% url 'qa:home' %}">
                    <div class="input-group">
                        <input type="text" name="search" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                        <button class="btn btn-secondary" type="submit">Go!</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header"><a href="{% url 'qa:categories' %}">Categories</a></h5>
          <div class="card-body">
              <ul class="list-group list-group-flush">
                  {% for c in top_categories %}
                      <li class="list-group-item d-flex justify-content-between align-items-center">
                      <a href="{% url 'qa:category' a_id=c.id %}">{{ c.name }}&nbsp;
                          <span class="badge badge-primary badge-pill">{{ c.num_questions }}</span></a></li>
                  {% endfor %}
              </ul>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
        <h5 class="card-header"><a href="{% url 'qa:popular' %}">Popular Questions</a></h5>
          <div class="card-body">
               <ul class="list-group list-group-flush">
                   {% for t in top %}
                       <li class="list-group-item d-flex justify-content-between align-items-center">
                       <a href="{% url 'qa:question' qn_id=t.id %}">{{ t.title }}</a></li>
                   {% endfor %}
               </ul>
          </div>
        </div>

</div>

templates/signin.html

{% extends 'components/header.html' %}


{% block content %}
<center>
    <!-- <div class="blob_1"> -->
        <svg class="blob_1" width="146" height="150" viewBox="0 0 146 150" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 75C0 18.75 18.214 0 72.8558 0C127.498 0 145.712 18.75 145.712 75C145.712 131.25 127.498 150 72.8558 150C18.214 150 0 131.25 0 75Z" fill="#00C897"/>
        </svg>

        <svg class="blob_2" width="326" height="334" viewBox="0 0 326 334" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0.577271 167C0.577271 41.75 41.2551 0 163.289 0C285.322 0 326 41.75 326 167C326 292.25 285.322 334 163.289 334C41.2551 334 0.577271 292.25 0.577271 167Z" fill="#00D19E"/>
        </svg>
        <svg class="blob_3" width="436" height="418" viewBox="0 0 436 418" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M67.1589 144.614C83.9486 108.46 247.449 48.2897 285.159 64.3862C322.869 80.4828 385.631 237.233 368.841 273.386C352.052 309.54 188.552 369.71 150.841 353.614C113.131 337.517 50.3692 180.767 67.1589 144.614Z" fill="#FADB5F"/>
        </svg>
        
        <svg class="blob_4" width="300" height="300" viewBox="0 0 300 300" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M46.2102 103.79C57.7628 77.8423 170.263 34.6576 196.21 46.2102C222.158 57.7627 265.342 170.263 253.79 196.21C242.237 222.158 129.737 265.342 103.79 253.79C77.8424 242.237 34.6577 129.737 46.2102 103.79Z" fill="#EF4E4E"/>
        </svg>
        
            
            

    <!-- </div> -->
    <div class="blob_2"></div>
    <div class="signin__main">
        <h1>Let&apos;s Connect!</h1>
        <form action="{% url 'signin' %}" method="post">
            {% csrf_token %}
            <div class="user_pass_main">
                <label >
                    <br>
                    Email
                    <br>
                    <input id="user_email" name="email" type="email"  required>
                </label>
                <label >
                    <br>
                    Password
                    <br>

                    <input id="user_password" name="password" type="password" minlength="8" required>
                </label>
    
            </div>
            <div style="width: 100%;text-align: left;">

                <a href="{% url 'forgot_password' %}">Forgot Password?</a>
            </div>
            <br>
            <br>

            <div style="width: 100%;text-align: right;">

                    <button type="submit">Connect &nbsp;</button>
            </div>
        </form>
        <br>
        <br>
        <br>
        <br>
        <br>

        <span>Don&apos;t already have an account? </span><a href="{% url 'verify_email' %}">create one</a>

    </div>

</center>
{% endblock content %}




templates/signup2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    {% load static %}
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/Sign-up.css' %}">
    <!-- link awesome icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <title>CONFAB: Sign-Up Page</title>
</head>


<body>
    <div class="body">

        <header>
            <!-- <img src="Rectangle 1.svg" alt="Rectangle" class="rectangle"> -->
            
            
            
            <a href="home.html"><span class="C">
                C
                </span>
                <span class="onfab">
                    ONFAB
                </span>
            </a>

        </header>
        <svg preserveAspectRatio="none" width="100VW" height="194" viewBox="0 0 1920 194" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect width="100VW" height="194" fill="white"/>
                <path d="M514.224 99.3881C607.024 80.3875 696.88 46.3306 789.424 25.6747C921.248 -3.76844 1058.53 -5.547 1190.14 24.9879C1318.05 54.5895 1450.67 126.789 1577.06 163.469C1689.14 196.012 1811.5 209.412 1920 168.752V0H0V48.162C163.945 116.582 341.781 134.298 514.224 99.3881Z" fill="#EDF2F6"/>
            </svg>
            <div class="container">
            <form action="{% url 'signup' email_hash %}" method="post">
            <div class="up">
                <div class="left-1">
                    <i class="fa-solid fa-angle-left"></i>
                    <a href=""> Back </a>
                </div>
                <div class="right-1">
                    <div class="top-1" style="font-size: 10;">
                        Step 2 of 2
                    </div>
                    <div class="down-1">
                        Signup
                    </div>
                </div>
            </div>
            <div class="middle">
                <div class="middle-top"><br>Create your account <br>
                    <p>Fill the detail bellow to submit register account. </p>
                </div>
                <div class="hero-1">
                    <div class="first">
                        <div class="input-box2">

                            <!-- bootstrap -->
                            <h6>Select your semester</h6>
                            <select name="sem" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                                <option selected>Open this select menu</option>
                                <option value="1">1st Semester</option>
                                <option value="2">2nd Semester</option>
                                <option value="3">3rd Semester</option>
                                <option value="4">4th Semester</option>
                                <option value="5">5th Semester</option>
                                <option value="6">6th Semester</option>
                                <option value="7">7th Semester</option>
                                <option value="8">8th Semester</option>
                              </select>




                            <div class="first">

                                <h6>Select your branch</h6>


                                <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="major">
                                    <option selected>Open this select menu</option>
                                     <option value="1">Computer Engineering</option>
                                    <option value="2">Computer Science & Engineering</option>
                                     <option value="3">Information Technolog</option>
                                     <option value="4">Electrical Engineering</option>
                                     <option value="5">Civil Engineering</option>
                                     <option value="6">Mechanical Engineering</option>
                                        <option value="7">Electronics & Communication Engineering</option>
                                     <option value="8">Physiotherapy</option>
                                     </select>
                                     

                            </div>

                            <div class="col-12">
                                <h6>Enter Password</h6>
                                <label class="visually-hidden" for="inlineFormInputGroupUsername">password</label>
                                <div class="input-group">
                                    <div class="input-group-text"><i class="fa-solid fa-lock"></i></div>
                                    <input type="password" placeholder="Type your password. Minimum length of 8 character" name="password">                                </div>
                            </div>
                            <div class="col-12">
                                <h6>Re-Enter Password</h6>
                                <label class="visually-hidden" for="inlineFormInputGroupUsername">re_password</label>
                                <div class="input-group">
                                    <div class="input-group-text"><i class="fa-solid fa-lock"></i></div>
                                    <input type="password" placeholder="Re-Password" name="re_password">                                </div>
                                <div class="hero-3">

                                    <p>By signing in, you're agree to our<a href=""> Terms & Condition</a> and <a href=""> Privacy Policy</a>.</p><br>
                                </div>
                            </div>
                            <div class="down">
                                    {% csrf_token %}
                                    {{ request.get_full_path }}
                                    <div class="down">                              <button class="button-5" role="button" type="submit">Continue</button>                              <div class="dowww">                                
                                    <p>Already have account? <a href="{% url 'signin' %}">Login</a></p>
                                </div>
                            </div>
                        </div>


             



                        <div class="images">
                            <div class="element1">
                                <svg preserveAspectRatio="none" width="147" height="136" viewBox="0 0 147 136" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M17.7502 16.5C40.6077 -4.615 106.393 -4.615 129.25 16.5C152.108 37.615 152.108 98.385 129.25 119.5C106.393 140.615 40.6077 140.615 17.7502 119.5C-5.10726 98.385 -5.10726 37.615 17.7502 16.5Z" fill="#FADB5F"/>
                                </svg>
                            </div>

                            <div class="element2">
                                <svg preserveAspectRatio="none" width="110" height="110" viewBox="0 0 110 110" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M1.03154 38.5C4.83091 26.0728 59.1546 -2.81162 71.5818 0.987751C84.0089 4.78712 112.893 59.1108 109.094 71.538C105.295 83.9651 50.9709 112.85 38.5438 109.05C26.1166 105.251 -2.76783 50.9271 1.03154 38.5Z" fill="#F9703E"/>
                                    </svg>
                            </div>
                            <div class="element4">
                                <svg preserveAspectRatio="none" width="181" height="181" viewBox="0 0 181 181" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M39.2042 39.2652C90.4695 -12 90.4695 -12 141.735 39.2652C193 90.5305 193 90.5305 141.735 141.796C90.4695 193.061 90.4695 193.061 39.2042 141.796C-12.061 90.5305 -12.061 90.5305 39.2042 39.2652Z" fill="#40C3F7"/>
                                    </svg>
                            </div>
                            <div class="element6">
                                
                            </div>
                            <div class="element7">
                               
                                    
                            </div>
                            <div class="element8">
                                <svg preserveAspectRatio="none"  width="118" height="117" viewBox="0 0 118 117" fill="none" xmlns="http://www.w3.org/2000/svg">
                                 
                                    <defs>
                                    <filter id="filter0_d_167_143" x="0.731567" y="0.177399" width="116.746" height="116.746" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                                    <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                                    <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
                                    <feOffset dy="4"/>
                                    <feGaussianBlur stdDeviation="2"/>
                                    <feComposite in2="hardAlpha" operator="out"/>
                                    <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
                                    <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_167_143"/>
                                    <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_167_143" result="shape"/>
                                    </filter>
                                    </defs>
                                    </svg>
                                    
                            </div>
                            <div class="element9">
                              
                            </div>

                            {% comment %} {% comment %} <img src="Element1.svg" alt="pink" class="element1">
                            <img src="Element2.svg" alt="He" class="element2"> {% endcomment %}
                            <!-- <img src="Element3.svg" alt="Hel" class="element3"> -->
                            {% comment %} <img src="Element6.svg" alt="Hell" class="element4"> {% endcomment %}
                            {% comment %} <!-- <img src="Element5.svg" alt="Hello" class="element5"> --> {% endcomment %} 
                           
                        </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </form>
                    <div class="footer">

                    </div>
</body>

</html>

templates/signup233.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    {% load static %}
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <link rel="stylesheet" href="{% static 'styles/signin.css' %}">
    <title>Sign Up</title>
  </head>
 <body> 
    <br><br><br><br><br><br><br><br>
    <center>
        <div style="width: 50vw">
            Create Account
            <br/>
    <form method="post" action="{{request.get_full_path}}">
        {% csrf_token %}
        <select class="form-select" aria-label="Major" name="major">
            <option value="CE">Computer Engineering</option>
            <option value="MECH">Mechenical Engineering</option>
            <option value="CIVIL">Civil Engineering</option>
            <option value="MBBS">MBBS</option>


        </select>
        <br/>

        <select class="form-select" aria-label="Year" name="year">
            <option value="1">1st</option>
            <option value="2">2nd</option>
            <option value="3">3rd</option>
            <option value="4">4th</option>

        </select>  
        <br/>

        <div class="col-auto">
            <label for="inputPassword2" class="visually-hidden">Password</label>
            <input type="password" name="password" class="form-control" id="inputPassword2" placeholder="Password">
        </div>
        <br/>

          <div class="col-auto">
            <label for="inputPassword2" class="visually-hidden">Re-Password</label>
            <input type="password" name="re_password" class="form-control" id="inputPassword2" placeholder="Re-Password">
          </div>
          <br/>
                
          <button type="submit" class="btn btn-primary">Create Account</button>

    </form>
</div>
</center>
 </body>
 </html>

templates/verify_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <title>Verify Email</title>
</head>
<body>

    {% for message in messages %}
        {% if message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% else %}

            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
    {% endfor %}

    <h3>Step-1: Verify Your Email</h3>
    <form action="{% url 'verify_email' %}" method="post">
        {% csrf_token %}

        <input type="email" placeholder="Enter Student e-mail" name="student_email">
        <button type="submit">Send Verification Link</button>

    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>

templates/whatisconfab.html
<!DOCTYPE html>
<html lang="en">
<head>

<h1>so what our site does offer more than it's literal meaning?</h1>
<h2>it offers the privacy the all time favourite of human beings </h2>
<h1>what does it actually do to provide the privacy?</h1>
<h2>well it doesnt take your username thus providing you anominity</h2>
<h1>so let's take all the points together and put it together so it can make sense,shall we?</h1>
<h2>confab is an informal discussion forum which is confined to a paticular organization which gives you anominity to answer or ask any question without any fear of being juged as it doesnt have ypur username</h2>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <title>Bootstrap Example</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="p-3 m-0 border-0 bd-example">

    <!-- Example Code -->
    
    <p>
      <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
        meaning of confab:
      </button>
    </p>
    <div style="min-height: 120px;">
      <div class="collapse collapse-horizontal" id="collapseWidthExample">
        <div class="card card-body" style="width: 300px;">
          an informal private conversation or discussion

            <!-- Example Code -->
          </div>
        </div>
      </div>
      
            <p>
              <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
                so what our site does offer more than it's literal meaning?
              </button>
            </p>
            <div style="min-height: 120px;">
              <div class="collapse collapse-horizontal" id="collapseWidthExample2">
                <div class="card card-body" style="width: 300px;">
                  it offers the privacy the all time favourite of human beings               
                 </div>
              </div>
            </div>
       
    <!-- End Example Code -->
  </body>
</html>